/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class suhu2 extends javax.swing.JFrame {

    /**
     * Creates new form suhu2
     */
    public suhu2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtinput2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbCelcius1 = new javax.swing.JRadioButton();
        rbFahrenheit1 = new javax.swing.JRadioButton();
        rbCalvin1 = new javax.swing.JRadioButton();
        rbCelcius2 = new javax.swing.JRadioButton();
        rbFahrenheit2 = new javax.swing.JRadioButton();
        rbCalvin2 = new javax.swing.JRadioButton();
        btncalcu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        txtInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtinput2.setText("input");

        jLabel2.setText("from");

        jLabel3.setText("to");

        rbCelcius1.setText("celcius");
        rbCelcius1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCelcius1ActionPerformed(evt);
            }
        });

        rbFahrenheit1.setText("fahrenheit");

        rbCalvin1.setText("calvin");

        rbCelcius2.setText("celcius");

        rbFahrenheit2.setText("fahrenheit");

        rbCalvin2.setText("calvin");

        btncalcu.setText("calculate");
        btncalcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcuActionPerformed(evt);
            }
        });

        jLabel4.setText("result");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtinput2)
                                .addGap(18, 18, 18)
                                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(44, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbCelcius1)
                            .addComponent(rbFahrenheit1)
                            .addComponent(rbCalvin1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbCalvin2)
                            .addComponent(rbCelcius2)
                            .addComponent(rbFahrenheit2))
                        .addGap(14, 14, 14))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncalcu, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtinput2)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCelcius2)
                    .addComponent(rbCelcius1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFahrenheit1)
                    .addComponent(rbFahrenheit2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCalvin1)
                    .addComponent(rbCalvin2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncalcu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCelcius1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCelcius1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCelcius1ActionPerformed

    private void btncalcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcuActionPerformed
        // TODO add your handling code here:
        double Input = 0;
        float Result = 0;
        String a;
        Double input = Double.parseDouble(txtInput.getText());
        
        if(rbCelcius1.isSelected() && rbCelcius2.isSelected()){
            Result = (float) Input;
            a = String.valueOf(Result);
            txtResult.setText(a);
        }
        if(rbCelcius1.isSelected() && rbFahrenheit2.isSelected()){
            Result = (float) (input * 9 / 5 +32);
            a = String.valueOf(Result);
            txtResult.setText(a);
        }
        if(rbCelcius1.isSelected() && rbCalvin2.isSelected()){
            Result = (float) (Input + 273);
            a = String.valueOf(Result);
            txtResult.setText(a);
        }
        if(rbFahrenheit1.isSelected() && rbCelcius2.isSelected()){
            Result = (float) ((Input - 32) * 5 / 9);
            a = String.valueOf(Result);
            txtResult.setText(a);
        }
        if(rbFahrenheit1.isSelected() && rbFahrenheit2.isSelected()){
            Result = (float) Input;
            a = String.valueOf(Result);
            txtResult.setText(a);
        }
        if(rbFahrenheit1.isSelected() && rbCalvin2.isSelected()){
            Result = (float) ((input - 32)*5/9+273);
            a = String.valueOf(Result);
            txtResult.setText(a);
        }
        if(rbCalvin1.isSelected() && rbFahrenheit2.isSelected()){
            Result = (float) (Input-273);
            a = String.valueOf(Result);
            txtResult.setText(a);
        }
        if(rbCalvin1.isSelected() && rbFahrenheit2.isSelected()){
            Result = (float) ((Input - 273)*9/5+32);
            a = String.valueOf(Result);
            txtResult.setText(a);
        }
        if(rbCalvin1.isSelected()&& rbFahrenheit2.isSelected ()){
            Result = (float) Input;
            a = String.valueOf(Result);
            txtResult.setText(a);
        }
    
    }//GEN-LAST:event_btncalcuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(suhu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(suhu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(suhu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(suhu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new suhu2().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbCalvin1;
    private javax.swing.JRadioButton rbCalvin2;
    private javax.swing.JRadioButton rbCelcius1;
    private javax.swing.JRadioButton rbCelcius2;
    private javax.swing.JRadioButton rbFahrenheit1;
    private javax.swing.JRadioButton rbFahrenheit2;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextField txtResult;
    private javax.swing.JLabel txtinput2;
    // End of variables declaration//GEN-END:variables
}
